from typing import Any, Protocol

from .models import BackendExecution, Capability, OperationPlan


class Backend(Protocol):
    name: str

    async def discover(self) -> list[Capability]: ...
    async def resolve_target(self, plan: OperationPlan) -> dict[str, Any]: ...
    async def validate(self, plan: OperationPlan, capability: Capability) -> None: ...
    async def execute(self, plan: OperationPlan, capability: Capability) -> BackendExecution: ...
    async def readback(self, plan: OperationPlan, capability: Capability) -> Any: ...
    def compare(self, plan: OperationPlan, actual: Any) -> bool: ...
